### ISSUE TITLE
[bug] Can't make it work for PyCharm

### ISSUE THREAD

**Issue by jguillon** [tilt-dev/tiltfile.tmbundle#1]
Hi!

I was able to import the bundle under PyCharm, but it doesn't seem to effectively work in the text editor. Am I missing something? Is there a way to debug it locally?

<img width="982" alt="Capture d’écran 2022-06-20 à 10 15 53" src="https://user-images.githubusercontent.com/2573188/174556835-7a7025f5-7d51-4103-bbd8-6f60651dbc96.png">

<details>
  <summary>Versions [Click to expand]</summary>

> PyCharm 2021.2.4 (Professional Edition)
  Build #PY-212.5712.39, built on December 21, 2021
  Runtime version: 11.0.13+8-b1504.49 x86_64
  VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
  macOS 12.4
  GC: G1 Young Generation, G1 Old Generation
  Memory: 2048M
  Cores: 12
  Registry: ide.balloon.shadow.size=0
  Non-Bundled Plugins: org.jetbrains.plugins.go-template (212.5712.51), me.lensvol.blackconnect (0.5.0), name.kropp.intellij.makefile (212.5712.51), com.nerdscorner.android.plugin.github (2.1.1), mobi.hsz.idea.gitignore (4.3.0), com.mallowigi (50.2.0), com.intellij.kubernetes (212.5712.14), org.toml.lang (0.2.155.4114-212), PlantUML integration (5.13.0), com.koxudaxi.poetry (1.1.5-212), com.jetbrains.intellij.datalore (0.1.14-212), ru.adelf.idea.dotenv (2022.1), com.chrisrm.idea.MaterialThemeUI (6.9.1)
</details>

**Comment by milas** [comment]
When you say it does not work effectively in the editor, do you mean that there's no syntax highlighting at all?

**Comment by jguillon** [comment]
Not at all indeed! I tried to disable my Material Theme, to reload, restart, and again. But nothing seems to have any effect on Tiltfiles syntax highlighting.

**Comment by milas** [comment]
Is your file named `Tiltfile` or something else?

In PyCharm Preferences, go to `Editor > File Types` and look to see if there's an association for `Tiltfile` under something else, e.g. "Text".

You can also try adding explicit mapping(s) in that same section under "Files supported via TextMate bundles":
<img width="1137" alt="TextMate bundle file associations in JetBrains IDEs" src="https://user-images.githubusercontent.com/841263/176276620-f4607a01-f4ce-4e3e-be19-99376b8b340e.png">

I just tested a fresh install of PyCharm Professional 2022.1.3 w/o any imported settings and highlighting worked after importing the bundle as described in the README here/JetBrains docs. (I did NOT need to add a manual mapping like I suggested above.) I'm on macOS as well (12.4).

Beyond that, I don't see anything else in the [PyCharm docs](https://www.jetbrains.com/help/pycharm/tutorial-using-textmate-bundles.html), so you might need to ask JetBrains support for further help, unfortunately.

**Comment by jguillon** [comment]
It works now ! For obscure reasons, I had to manually add the mapping that you just described for it to work. Now, I removed the mapping and it still works...

Thanks a lot for your help. And keep on working on `tilt`, this tool is amazing ❤️

**Comment by milas** [comment]
Yay! I'm glad you got it working!

**Comment by tzelleke** [comment]
I had the same problem and was able to fix it by removing `Tiltfile` from the  Python File type (which I had manually defined before) and from `File type auto-detected by file content` (which had been added by PyCharm seemingly).

**Comment by guillaumebriday** [comment]
Hey 👋 

I have the same issue but the option "Files supported via TextMate bundles" doesn't show up at all in the File Types list.

Any idea what might be causing this?

Thanks in advance

**Comment by milas** [comment]
@guillaumebriday It looks like "Files supported via TextMate bundles" section of `Editor > File Types` is not in the latest version of the JetBrains IDEs.

The README in this repo links to the various specific IDE docs, but ensure you have the "TextMate Bundles" plugin activated and you can see the Tiltfile bundle under `Editor > TextMate Bundles`.

(I can confirm it's working correctly for me still in IntelliJ 2025.1.3.)

You might try right-clicking on an editor tab for a Tiltfile and choose "Associate with File Type..." -- you'll want this to be "Open matching files as text and auto-detect file type by content" so that it uses the TextMate bundle instead of being assigned to plaintext or something.

<img width="825" height="552" alt="Image" src="https://github.com/user-attachments/assets/035cba9a-39d9-44c8-bb63-0c82b3205cd4" />

**Comment by guillaumebriday** [comment]
Ahh, it works! Thanks 🙌

But now I also have files named Tiltfile-database, Tiltfile-api, Tiltfile-vue, and so on.

The problem is that I can’t associate these with the Tilt syntax — it only works for the file named exactly Tiltfile.

Any idea how I can associate all of them?

**Comment by milas** [comment]
I believe this is a limitation of the TextMate bundle format: we can give `fileTypes` which are either full filenames OR extensions:
https://github.com/tilt-dev/tiltfile.tmbundle/blob/5846e38f058f4a3d9638da7999725dfb4293f85f/Syntaxes/Tiltfile.tmLanguage#L5-L9

If you rename your files to be `database.tiltfile` / `api.tiltfile` / etc, that should get the highlighting working correctly across them all.
